[workspace]
members = [
    "abs_art",
    "abs_art-tokio",
    "abs_art-compio",
    "abs_art-smol",
    "abs_art-bridge",
    "abs_art-demo",
]
resolver = "3"

[workspace.package]
version = "0.2.2"
edition = "2024"
authors = ["lino <lino_snsalias@outlook.com>"]
license = "MIT/Apache-2.0"
description = "ABStraction of Asynchronous RunTime"
homepage = "https://github.com/ljsnogard/abs_art"
keywords = ["async", "async-runtime", "wrapper"]
categories = ["asynchronous"]
readme = "README.md"

[workspace.dependencies]
abs_art = { path = "abs_art" }
abs_art-tokio = { path = "abs_art-tokio" }
abs_art-compio = { path = "abs_art-compio" }
abs_art-smol = { path = "abs_art-smol" }
abs_art-bridge = { path = "abs_art-bridge" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time"] }
compio = { version = "0.19.*", features = ["time"] }
smol = { version = "2" }
