[package]
name = "abs_art"
version = "0.1.0"
edition = "2024"

authors = ["lino <lino_snsalias@outlook.com>"]
description = "ABStraction of Asynchronous RunTime"
homepage = "https://github.com/ljsnogard/abs_art"
keywords = ["async", "futures", "tokio", "smol", "compio", "wrapper"]
categories = ["no_std"]
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
join_handle = []
block_on = []
spawn_send = ["join_handle"]
spawn_local = ["join_handle"]
spawn_blocking = ["join_handle", "tokio/rt", "tokio/rt-multi-thread"]

runtime-tokio = ["dep:tokio"]
runtime-smol = ["dep:smol", "scoped-tls", "async-executor"]
runtime-compio = ["dep:compio"]

default = [
    # "runtime-compio",
    "runtime-tokio",
    # "runtime-smol",
    "block_on",
    "spawn_blocking",
    "spawn_send",
    "spawn_local",
]

[dependencies]
pin-project = { version = "1.1.*" }
pin-utils = { version = "0.1.0" }
compio = { version = "0.19.*", optional = true }
smol = { version = "2", optional = true }
tokio = { version = "1", features = ["rt", "rt-multi-thread"], optional = true }

scoped-tls = { version = "1", optional = true }
async-executor = { version = "1.5.*", optional = true }
