[package]
name = "abs_art-bridge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
abs_art        = { path = "../abs_art", version = "0.2.0" }
abs_art-tokio  = { path = "../abs_art-tokio", optional = true, version = "0.2.0" }
abs_art-compio = { path = "../abs_art-compio", optional = true, version = "0.2.0" }
abs_art-smol   = { path = "../abs_art-smol", optional = true, version = "0.2.0" }

[features]
# 通过 Cargo.toml 选择后端（必须且只能启用一个）
backend-tokio = ["dep:abs_art-tokio"]
backend-compio = ["dep:abs_art-compio"]
backend-smol = ["dep:abs_art-smol"]
